### ISSUE TITLE
Get MQTT Topic, server ip and port from user end?

### ISSUE THREAD

**Issue by prasad7676** [ArnieX/esp8266_relay_mqtt#2]
can you please help me to add MQTT Topic, server ip and port from user end?

**Comment by ArnieX** [comment]
Hi,

I haven't had a time and need to get that far, but it is quite well documented here:

https://github.com/tzapu/WiFiManager

So it will likely need just a few touches to get what you need. If you achieve it, please share your success.

Let me know if you have any more questions.

Martin

**Comment by ArnieX** [comment]
Hi @prasad7676,

check out my other project http://swifitch.cz/software here on GitHub, where I have implemented getting multiple settings from user. It should give you all information you need.

BR,

Martin
